services:
  webui:
    image: "ghcr.io/yummiii/sd-webui-forge-docker:latest"
    # build: .
    volumes:
      - "./data:/app/sd-webui"
    ports:
      - "17860:7860"
    environment:
      - "ARGS=--listen --enable-insecure-extension-acces"
      - "UI=forge-sd35"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
